export { EducationGovernancePlatform } from "./EducationGovernancePlatform"
export { default as GovernanceDashboard } from "./GovernanceDashboard"
export { default as SchoolManagement } from "./SchoolManagement"
export { default as PolicyCenter } from "./PolicyCenter"
export { default as LeaveManagement } from "./LeaveManagement"
export { default as AttendanceTracker } from "./AttendanceTracker"
export { default as DocumentTracker } from "./DocumentTracker"
export { default as NotificationsCenter } from "./NotificationsCenter"
export { default as ComplianceQA } from "./ComplianceQA"
export { default as FinanceManagement } from "./FinanceManagement"
