-- Enterprise NGO SaaS schema upgrade
-- Run against your Neon PostgreSQL database

-- ── 1. Extend subscription plan to include 'enterprise' tier ─────────────────
-- If you use an enum, extend it:
-- ALTER TYPE subscription_plan ADD VALUE IF NOT EXISTS 'enterprise';

-- ── 2. enterprise_projects ───────────────────────────────────────────────────
-- The application uses a client-generated UUID as the primary identifier (stored
-- in `id`). The SERIAL column here is the DB-internal PK; the `user_facing_id`
-- column stores the UUID generated by the application.
CREATE TABLE IF NOT EXISTS enterprise_projects (
  id              SERIAL PRIMARY KEY,
  user_id         TEXT NOT NULL,
  user_facing_id  TEXT NOT NULL,          -- UUID generated by the application
  name            TEXT NOT NULL,
  description     TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_enterprise_projects_user_id       ON enterprise_projects (user_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_enterprise_projects_ufid   ON enterprise_projects (user_facing_id);

-- ── 3. enterprise_project_files ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS enterprise_project_files (
  id          SERIAL PRIMARY KEY,
  project_id  INTEGER NOT NULL REFERENCES enterprise_projects(id) ON DELETE CASCADE,
  user_id     TEXT NOT NULL,
  file_name   TEXT NOT NULL,
  file_type   TEXT NOT NULL CHECK (file_type IN ('document', 'csv', 'other')),
  file_size   INTEGER,
  content     TEXT,
  uploaded_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_project_files_project_id ON enterprise_project_files (project_id);
CREATE INDEX IF NOT EXISTS idx_project_files_user_id    ON enterprise_project_files (user_id);

-- ── 4. organization_settings ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS organization_settings (
  id              SERIAL PRIMARY KEY,
  user_id         TEXT NOT NULL UNIQUE,
  org_name        TEXT,
  logo_url        TEXT,
  primary_color   TEXT DEFAULT '#5CC3EB',
  secondary_color TEXT DEFAULT '#8CB499',
  phone           TEXT,
  email           TEXT,
  address         TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_org_settings_user_id ON organization_settings (user_id);

-- ── 5. enterprise_reports ────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS enterprise_reports (
  id          SERIAL PRIMARY KEY,
  user_id     TEXT NOT NULL,
  project_id  INTEGER REFERENCES enterprise_projects(id) ON DELETE SET NULL,
  title       TEXT NOT NULL,
  body        TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_enterprise_reports_user_id ON enterprise_reports (user_id);

-- ── 6. Add enterprise columns to subscriptions / users KV table ──────────────
-- If you have a relational subscriptions table, add these columns:
--
-- ALTER TABLE subscriptions
--   ADD COLUMN IF NOT EXISTS plan TEXT NOT NULL DEFAULT 'basic'
--     CHECK (plan IN ('basic', 'pro', 'team', 'enterprise')),
--   ADD COLUMN IF NOT EXISTS has_ngo_module_access BOOLEAN NOT NULL DEFAULT FALSE;
--
-- ALTER TABLE users
--   ADD COLUMN IF NOT EXISTS has_ngo_module_access BOOLEAN NOT NULL DEFAULT FALSE;
--
-- Note: The application currently stores subscriptions as JSON blobs in Spark KV /
-- Neon KV tables. The `hasNgoModuleAccess` flag in that JSON is fully supported
-- by the TypeScript type `SubscriptionInfo.hasNgoModuleAccess` added in this PR.
